# Lighting Settings
gamma=1

# Player Movement Settings
player.maxSpeed=6.0
player.acceleration=40.0
player.groundDeceleration=30.0
player.airDeceleration=10.0
player.jumpUpSpeed=9.0
player.maxFallSpeed=15.0 
player.fallAcceleration=25.0
player.jumpEndEarlyGravityModifier=3.0 
player.coyoteTime=0.1
player.jumpBufferTime=0.15 
player.flySpeed=50.0

# World and Chunk Settings
world.chunkSizeX=16
world.chunkSizeY=16
world.chunkSizeZ=16
world.renderDistanceInChunks=16

# Debug Settings
debug.flyMode=1