# Lighting Settings
gamma=0.5
lightPositionX=100.0
lightPositionY=100.0
lightPositionZ=50.0

# Player Movement Settings
player.maxSpeed=6.0
player.acceleration=40.0
player.groundDeceleration=30.0
player.airDeceleration=10.0
player.jumpUpSpeed=9.0
player.maxFallSpeed=40.0 
player.fallAcceleration=25.0
player.jumpEndEarlyGravityModifier=3.0 
player.coyoteTime=0.1
player.jumpBufferTime=0.15 
