# Lighting Settings
gamma=1

# Player Movement Settings
player.maxSpeed=6.0
player.acceleration=40.0
player.groundDeceleration=30.0
player.airDeceleration=10.0
player.jumpUpSpeed=8.0
player.maxFallSpeed=25.0 
player.fallAcceleration=25.0
player.jumpEndEarlyGravityModifier=1.8 
player.coyoteTime=0.1
player.jumpBufferTime=0.15 
player.flySpeed=50.0
player.enablePlayerAirRoll=1

# World and Chunk Settings
world.chunkSizeX=16
world.chunkSizeY=16
world.chunkSizeZ=16
world.renderDistanceInChunks=12

# Debug Settings
debug.flyMode=1